name: Release (Production)

on:
  push:
    branches:
      - dev  
  workflow_dispatch:
  schedule:
    - cron: '0 17 14 12 *' 
jobs:
  merge-and-release:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Checkout main branch
        run: |
          git checkout main
          git pull origin main
      - name: Merge dev into main
        run: |
          git checkout main
          git merge dev --no-ff -m "Merge dev into main"
      - name: Push changes to main
        run: |
          git push origin main

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push
